services:
  lincidb:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT:-5432}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changem3}
      POSTGRES_USER: ${POSTGRES_USER:-linciuser}
      POSTGRES_DB: ${POSTGRES_DB:-linci}
  lincidb-migrations:
    image: redgate/flyway
    volumes:
      - ./flyway/sql:/flyway/sql
    environment:
      FLYWAY_URL: "jdbc:postgresql://${POSTGRES_HOST:-lincidb}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-linci}?user=${POSTGRES_USER:-linciuser}&password=${POSTGRES_PASSWORD:-changem3}"
    depends_on:
      - lincidb
    restart: on-failure
    command: migrate
  graphql:
    image: linci/graphql
    ports:
      - "18080:8080"
    depends_on:
      - lincidb-migrations
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changem3}
      POSTGRES_USER: ${POSTGRES_USER:-linciuser}
      POSTGRES_HOST: ${POSTGRES_HOST:-lincidb}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-linci}
  auth:
    image: node:20
    user: "node"
    working_dir: /home/node/auth
    ports:
      - "4001"
    depends_on:
      - lincidb-migrations
    environment:
      NODE_ENV: production
      PORT: ${AUTH_PORT:-4001}
    volumes:
      - ./auth/:/home/node/auth/
    command: npm start