name: "Graphql CI"

on:
  push:
    paths:
      - '.github/workflows/graphql-ci.yml'
      - 'graphql/**'

permissions:
  contents: read

jobs:
  build-graphql:
    name: Build Graphql
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # - name: Validate Gradle wrapper
      #   uses: gradle/wrapper-validation-action@v1

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: graphql


